### PR TITLE
fix for SDV 1.6

### PR DESCRIPTION
**Pull request by huancz**
main mod tested a little. Skill adapters for luck, magic and cooking skills build, but their respective mods are rejected by SMAPI => not tested.

Also closes dependabot PRs.

### CODE REVIEW

**Comment by XiNaru** [comment]
well thanks but a question:

in the orginal nexus page stands, there is native support for the luck skill included. i have the luck skill but i cant prestige the luck skill with thios update

**Comment by huancz** [comment]
@XiNaru As far as I know, there was never "native" support for luck skill. It was always adapter. Separate mod, glue between the two other mods.

You can try this build, if you confirm it works I can post it in the unofficial update thread.

[SkillPrestige.LuckSkill 1.2.4-unofficial.15-huancz.zip](https://github.com/Alphablackwolf/SkillPrestige/files/14821512/SkillPrestige.LuckSkill.1.2.4-unofficial.15-huancz.zip)

**Comment by XiNaru** [comment]
well i can only say what in the orginal mod thread stand :P
i try it thanks

**Comment by XiNaru** [comment]
okay it seems work, the mnu open (no images but the text stands: https://images.xinaru.de/index.php/s/YFD5rcdfRFewrEQ/preview) but then i have 2 other questions.

1. Is it possible to add translation folders? the Luck skills seems to be in german to, but the skill prestige mod only english, i i would make an german translation. or if you can give me all strings, i cann send you the translated back to add it.

2. the other question. is it possible to CREATE new prestige adapters?
there are actually 3 updated skills, that dont have an prestige adapter in the moment. 
Socializing: https://www.nexusmods.com/stardewvalley/mods/14142
Binning: https://www.nexusmods.com/stardewvalley/mods/14073
Traveling: https://www.nexusmods.com/stardewvalley/mods/16820


all these 3 skills i use actually and they work. it were very nice if i had an integration :)

**Comment by huancz** [comment]
https://forums.stardewvalley.net/threads/unofficial-mod-updates.2096/page-173#post-123972

**Comment by XiNaru** [comment]
> https://forums.stardewvalley.net/threads/unofficial-mod-updates.2096/page-173#post-123972

well cooking and magic dont updated yet xd 
the other 3 i ask, are new skills, that doesnt have an adapter at the moment , thats because i ask :)

**Comment by Alphablackwolf** [comment]
Updated the official mod, didn't go through the merge request as I had in-flight changes as well. Thank you all for picking up so much slack!

**Pull request closed without merging**
